Changed readme file
pooja-patil0824/my-polymer-app pull request #1
Opened 2018-01-26 23:38 UTC by Siddhant-awati

Please merge my changes to master

2018-01-26 23:44 UTC, pooja-patil0824 requested changes
fix comments

2018-01-26 23:44 UTC, pooja-patil0824 commented on README.md
> -## Viewing Your Application
dont remove this line

2018-01-26 23:44 UTC, pooja-patil0824 commented on README.md
> -This will create builds of your application in the `build/` directory, optimized to be served in production. You can then serve the built versions by giving `polymer serve` a folder to serve from:
add proper description

2018-01-26 23:44 UTC, pooja-patil0824 commented on README.md
> -$ polymer build
dont use var, instead use let or const

2018-01-26 23:44 UTC, Siddhant-awati commented on README.md
> -## Viewing Your Application
fixed changes and pushed

2018-01-26 23:45 UTC, merged

2018-02-09 15:01 UTC, Siddhant-awati reviewed
Done.